static const int PROT_NONE = 0;
static const int PROT_READ = 1;
static const int PROT_WRITE = 2;
static const int PROT_EXEC = 4;
static const int MAP_ANON = 32;
static const int MAP_FILE = 0;
static const int MAP_FIXED = 16;
static const int MAP_PRIVATE = 2;
static const int MAP_SHARED = 1;
static const int MS_ASYNC = 1;
static const int MS_SYNC = 4;
static const int MS_INVALIDATE = 2;
static const int MADV_NORMAL = 0;
static const int MADV_SEQUENTIAL = 2;
static const int MADV_RANDOM = 1;
static const int MADV_WILLNEED = 3;
static const int MADV_DONTNEED = 4;
static const int MREMAP_MAYMOVE = 1;
static const int MREMAP_FIXED = 2;

void *mremap(void *old_addr, size_t old_size, size_t new_size, int flags, void *new_addr);
