double acos(double);
double asin(double);
double atan(double);
double atan2(double, double);
double cos(double);
double sin(double);
double tan(double);
double acosh(double);
double asinh(double);
double atanh(double);
double cosh(double);
double sinh(double);
double tanh(double);
double exp(double);
double exp2(double); 
double expm1(double); 
double log(double);
double log10(double);
double log2(double);
double log1p(double);
double logb(double);
double modf(double, double *);
double ldexp(double, int);
double frexp(double, int *);
int ilogb(double);
double scalbn(double, int);
double scalbln(double, long int);
double fabs(double);
double cbrt(double);
double hypot(double, double);
double pow(double, double);
double sqrt(double);
double erf(double);
double erfc(double);
double tgamma(double);
double ceil(double);
double floor(double);
double nearbyint(double);
double rint(double);
long int lrint(double);
double round(double);
long int lround(double);
double trunc(double);
double fmod(double, double);
double remainder(double, double);
double remquo(double, double, int *);
double copysign(double, double);
double nan(const char *);
double nextafter(double, double);
double nexttoward(double, long double);
double fdim(double, double);
double fmax(double, double);
double fmin(double, double);
double fma(double, double, double);
